"out:\n"
"\tpop rax\n"
"\tsub rsp, 64\n"
"\tpush rbp\n"
"\tmov rbp, rsp\n"
"\tadd rbp, 72\n"
"\tpush rbx\n"
"\tpush rcx\n"
"\tpush rdx\n"
"\tpush rdi\n"
"\tpush rsi\n"
"\tpush r9\n"
"\tmov r9, rax\n"
"\tmov rdi, rbp\n"
"\tsub rdi, 8\n"
"\tmov qword rax, [rbp]\n\n""
"\tmov rbx, 01h\n"
"\tmov rdx, rax\n"
"\tmov rcx, 64\n"
"llPrintingLoop:\n"
"\tmov rdx, rax\n"
"\tcmp rcx, 0x00\n"
"\tje llPrintingLoopEnd\n"
"\tand rdx, rbx\n"
"\tadd rdx, 0x30\n"
"\tmov byte [rdi], dl\n"
"\tdec rdi\n"
"\tshr rax, 1\n"
"\tdec rcx\n"
"\tjmp llPrintingLoop\n"
"llPrintingLoopEnd:\n"
"\tmov rax, 0x01\n"
"\tmov rsi, rdi\n"
"\tmov rdi, 0x01\n"
"\tmov rdx, 64\n"
"\tsyscall\n"
"\tsub rbp, 8\n"
"\tmov [rbp], r9\n"
"\tpop r9\n"
"\tpop rsi\n"
"\tpop rdi\n"
"\tpop rdx\n"
"\tpop rsi\n"
"\tpop rbx\n"
"\tpop rbp\n"
"\tadd rsp, 56\n"
"\tret\n\n"